/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Product, Language } from '../types';

export const PRODUCTS: Product[] = [
  {
    id: 'curd-pot',
    name: 'Vedic Curd Pot',
    benefit: 'Maintains pH balance and adds natural minerals for better digestion.',
    category: 'storage',
    imageUrl: 'https://images.unsplash.com/photo-1598502138823-8a50d633c054?auto=format&fit=crop&q=80&w=800',
    price: 450,
    size: '1.5 Liters',
    usageInstructions: 'Soak in water for 24 hours before first use. Hand wash only.',
    availability: 'in-stock',
    ecoScore: 98,
    plasticReduced: '1.2kg plastic containers/year',
    artisanId: 'ravi-123'
  },
  {
    id: 'terracotta-bottle',
    name: 'Ancient Cool Bottle',
    benefit: 'Natural cooling via micro-porosity; 100% BPA and lead-free.',
    category: 'wellness',
    imageUrl: 'https://images.unsplash.com/photo-1616781296180-278cd781894b?auto=format&fit=crop&q=80&w=800',
    price: 350,
    size: '1 Liter',
    usageInstructions: 'Clean daily with a soft brush. Do not use soap.',
    availability: 'in-stock',
    ecoScore: 99,
    plasticReduced: '365 plastic bottles/year',
    artisanId: 'ravi-123'
  },
  {
    id: 'cooking-handi',
    name: 'Heritage Cooking Handi',
    benefit: 'Circulates steam to retain 100% of food nutrients and natural flavor.',
    category: 'cooking',
    imageUrl: 'https://images.unsplash.com/photo-1590133323218-f22397ee01bc?auto=format&fit=crop&q=80&w=800',
    price: 850,
    size: '3 Liters',
    usageInstructions: 'Use on low to medium flame. Avoid sudden temperature changes.',
    availability: 'on-order',
    ecoScore: 96,
    plasticReduced: 'Replaces aluminum cookware',
    artisanId: 'ravi-123'
  },
  {
    id: 'clay-kulhad-set',
    name: 'Royal Kulhad Set',
    benefit: 'Enhances the aroma of tea/coffee with a unique earthy flavor.',
    category: 'wellness',
    imageUrl: 'https://images.unsplash.com/photo-1621275014101-4997e377667c?auto=format&fit=crop&q=80&w=800',
    price: 250,
    size: 'Set of 6',
    usageInstructions: 'Single use recommended for authentic taste, or wash carefully for home use.',
    availability: 'in-stock',
    ecoScore: 100,
    plasticReduced: 'Eliminates paper/plastic cups',
    artisanId: 'ravi-123'
  },
  {
    id: 'water-jug',
    name: 'Traditional Water Jug',
    benefit: 'Naturally purifies water and keeps it at the perfect drinking temperature.',
    category: 'storage',
    imageUrl: 'https://images.unsplash.com/photo-1601633615367-b505508a8ba3?auto=format&fit=crop&q=80&w=800',
    price: 650,
    size: '5 Liters',
    usageInstructions: 'Keep in a cool, ventilated place for maximum cooling effect.',
    availability: 'in-stock',
    ecoScore: 97,
    plasticReduced: 'Replaces plastic refrigerators partially',
    artisanId: 'ravi-123'
  }
];

export const UI_STRINGS: Record<Language, Record<string, string>> = {
  en: {
    catalog: "Product Catalog",
    createCard: "Create Story Card",
    digitalCard: "Digital Card",
    buyNow: "Buy Now",
    customize: "Customize",
    artisanProfile: "Artisan Profile",
    ecoMode: "Eco Impact",
    benefits: "Benefits",
    price: "Price",
    size: "Size",
    searchPlaceholder: "Search products or health benefits...",
    favorites: "Favorites",
    settings: "Settings",
    saveProfile: "Save Branding Profile",
    storiesShared: "Stories Shared",
    availability: "Check Availability",
    scanning: "Scanning Legacy...",
    whatsapp: "WhatsApp",
    download: "Download",
    scanStory: "SCAN STORY",
    traditional: "Traditional",
    minimal: "Minimal",
    festival: "Festival",
    cooking: "Cooking",
    storage: "Storage",
    wellness: "Wellness",
    all: "All",
    filterTitle: "Filters",
    applyFilters: "Apply Filters",
    resetFilters: "Reset",
    priceRange: "Price Range",
    minEcoScore: "Min Eco-Score",
    availabilityFilter: "Status",
    inStock: "In Stock",
    onOrder: "On Order",
    maxPrice: "Max Price"
  },
  kn: {
    catalog: "ಉತ್ಪನ್ನಗಳ ಪಟ್ಟಿ",
    createCard: "ಕಾರ್ಡ್ ರಚಿಸಿ",
    digitalCard: "ಡಿಜಿಟಲ್ ಕಾರ್ಡ್",
    buyNow: "ಈಗ ಖರೀದಿಸಿ",
    customize: "ಕಸ್ಟಮೈಜ್",
    artisanProfile: "ಕುಶಲಕರ್ಮಿ ಪ್ರೊಫೈಲ್",
    ecoMode: "ಪರಿಸರ ಪರಿಣಾಮ",
    benefits: "ಪ್ರಯೋಜನಗಳು",
    price: "ಬೆಲೆ",
    size: "ಗಾತ್ರ",
    searchPlaceholder: "ಹುಡುಕಿ...",
    favorites: "ಮೆಚ್ಚಿನವುಗಳು",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    saveProfile: "ಪ್ರೊಫೈಲ್ ಉಳಿಸಿ",
    storiesShared: "ಹಂಚಲಾದ ಕಥೆಗಳು",
    availability: "ಲಭ್ಯತೆ ಪರಿಶೀಲಿಸಿ",
    scanning: "ಸ್ಕ್ಯಾನ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    whatsapp: "ವಾಟ್ಸಾಪ್",
    download: "ಡೌನ್ಲೋಡ್",
    scanStory: "ಕಥೆ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    traditional: "ಸಂಪ್ರದಾಯ",
    minimal: "ಕನಿಷ್ಠ",
    festival: "ಹಬ್ಬದ",
    cooking: "ಅಡುಗೆ",
    storage: "ಸಂಗ್ರಹಣೆ",
    wellness: "ಆರೋಗ್ಯ",
    all: "ಎಲ್ಲಾ",
    filterTitle: "ಫಿಲ್ಟರ್‌ಗಳು",
    applyFilters: "ಫಿಲ್ಟರ್ ಅನ್ವಯಿಸಿ",
    resetFilters: "ಮರುಹೊಂದಿಸಿ",
    priceRange: "ಬೆಲೆ ಶ್ರೇಣಿ",
    minEcoScore: "ಕನಿಷ್ಠ ಇಕೋ-ಸ್ಕೋರ್",
    availabilityFilter: "ಸ್ಥಿತಿ",
    inStock: "ದಾಸ್ತಾನು ಇದೆ",
    onOrder: "ಆರ್ಡರ್ ಮೇಲೆ",
    maxPrice: "ಗರಿಷ್ಠ ಬೆಲೆ"
  },
  hi: {
    catalog: "उत्पाद सूची",
    createCard: "कहानी कार्ड बनाएं",
    digitalCard: "डिजिटल कार्ड",
    buyNow: "अभी खरीदें",
    customize: "अनुकूलित करें",
    artisanProfile: "कारीगर प्रोफ़ाइल",
    ecoMode: "पर्यावरण प्रभाव",
    benefits: "लाभ",
    price: "कीमत",
    size: "आकार",
    searchPlaceholder: "खोजें...",
    favorites: "पसंदीदा",
    settings: "सेटिंग्स",
    saveProfile: "प्रोफ़ाइल सहेजें",
    storiesShared: "साझा की गई कहानियाँ",
    availability: "उपलब्धता जांचें",
    scanning: "स्कैनिंग...",
    whatsapp: "व्हाट्सएप",
    download: "डाउनलोड",
    scanStory: "कहानी स्कैन करें",
    traditional: "पारंपरिक",
    minimal: "मिनिमल",
    festival: "त्योहार",
    cooking: "खाना पकाना",
    storage: "भंडारण",
    wellness: "कल्याण",
    all: "सब",
    filterTitle: "फ़िल्टर",
    applyFilters: "फ़िल्टर लागू करें",
    resetFilters: "रीसेट करें",
    priceRange: "कीमत सीमा",
    minEcoScore: "न्यूनतम ईको-स्कोर",
    availabilityFilter: "स्थिति",
    inStock: "स्टॉक में",
    onOrder: "ऑर्डर पर",
    maxPrice: "अधिकतम कीमत"
  },
  ta: {
    catalog: "தயாரிப்பு பட்டியல்",
    createCard: "கதை அட்டையை உருவாக்கு",
    digitalCard: "டிஜிட்டல் அட்டை",
    buyNow: "இப்போது வாங்கு",
    customize: "தனிப்பயனாக்கு",
    artisanProfile: "கைவினைஞர் சுயவிவரம்",
    ecoMode: "சுற்றுச்சூழல் தாக்கம்",
    benefits: "நன்மைகள்",
    price: "விலை",
    size: "அளவு",
    searchPlaceholder: "தேடு...",
    favorites: "விருப்பமானவை",
    settings: "அமைப்புகள்",
    saveProfile: "சுயவிவரத்தைச் சேமி",
    storiesShared: "பகிரப்பட்ட கதைகள்",
    availability: "இருப்பைச் சரிபார்க்கவும்",
    scanning: "ஸ்கேனிங்...",
    whatsapp: "வாட்ஸ்அப்",
    download: "பதிவிறக்கம்",
    scanStory: "கதையை ஸணே் செய்க",
    traditional: "பாரம்பரிய",
    minimal: "குறைந்தபட்ச",
    festival: "திருவிழா",
    cooking: "சமையல்",
    storage: "சேமிப்பு",
    wellness: "நலவாழ்வு",
    all: "எல்லாம்",
    filterTitle: "வடிகட்டிகள்",
    applyFilters: "வடிகட்டிகளைப் பயன்படுத்து",
    resetFilters: "மீட்டமை",
    priceRange: "விலை வரம்பு",
    minEcoScore: "குறைந்தபட்ச ஈக்கோ-ஸ்கோர்",
    availabilityFilter: "நிலை",
    inStock: "கையிருப்பில் உள்ளது",
    onOrder: "ஆர்டரில் உள்ளது",
    maxPrice: "அதிகபட்ச விலை"
  }
};
